# Generated by Django 2.0.5 on 2019-04-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='NoteSite',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Category'),
        ),
    ]
