# Generated by Django 2.0.5 on 2019-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='open_url',
            field=models.BooleanField(default=False),
        ),
    ]
