# Generated by Django 2.0 on 2019-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_auto_20190506_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
